=== kinnder/process-engineering/planning/src/test/resources/elements.dtd
<?xml encoding="UTF-8"?>
<!-- xml.mherman.org -->

<!ELEMENT elements (element)+>
<!ATTLIST elements
  xmlns CDATA #FIXED ''>

<!ELEMENT element (operation,objects,transformations)>
<!ATTLIST element
  xmlns CDATA #FIXED ''>

<!ELEMENT operation EMPTY>
<!ATTLIST operation
  xmlns CDATA #FIXED ''
  name CDATA #REQUIRED>

<!ELEMENT objects (object)+>
<!ATTLIST objects
  xmlns CDATA #FIXED ''>

<!ELEMENT transformations (transformation)+>
<!ATTLIST transformations
  xmlns CDATA #FIXED ''>

<!ELEMENT object (attributes?,links?)>
<!ATTLIST object
  xmlns CDATA #FIXED ''
  id CDATA #REQUIRED
  name CDATA #REQUIRED>

<!ELEMENT transformation EMPTY>
<!ATTLIST transformation
  xmlns CDATA #FIXED ''
  id CDATA #REQUIRED
  name CDATA #REQUIRED
  type (linkUpdate | valueUpdate) #REQUIRED
  value CDATA #REQUIRED>

<!ELEMENT attributes (attribute)+>
<!ATTLIST attributes
  xmlns CDATA #FIXED ''>

<!ELEMENT links (link)+>
<!ATTLIST links
  xmlns CDATA #FIXED ''>

<!ELEMENT attribute EMPTY>
<!ATTLIST attribute
  xmlns CDATA #FIXED ''
  name CDATA #REQUIRED
  type (boolean| string| object) #REQUIRED
  value CDATA #REQUIRED>

<!ELEMENT link EMPTY>
<!ATTLIST link
  xmlns CDATA #FIXED ''
  name CDATA #REQUIRED
  value CDATA #REQUIRED>

=== kinnder/process-engineering/planning/src/test/resources/elements.xml
<!DOCTYPE elements SYSTEM "elements.dtd">
<elements>
	<element>
		<operation name="Движение вправо" />
		<objects>
			<object name="материальная точка" id="#ID-1">
				<links>
					<link name="position" value="#ID-2" />
				</links>
			</object>
			<object name="точка" id="#ID-2">
				<attributes>
					<attribute name="occupied" type="boolean" value="true" />
				</attributes>
				<links>
					<link name="right-neighbor" value="#ID-3" />
					<link name="position" value="#ID-1" />
				</links>
			</object>
			<object name="точка" id="#ID-3">
				<attributes>
					<attribute name="occupied" type="boolean" value="false" />
				</attributes>
				<links>
					<link name="left-neighbor" value="#ID-2" />
				</links>
			</object>
		</objects>
		<transformations>
			<transformation type="linkUpdate" id="#ID-1"
				name="position" value="#ID-3" />
			<transformation type="linkUpdate" id="#ID-2"
				name="position" value="" />
			<transformation type="linkUpdate" id="#ID-3"
				name="position" value="#ID-1" />
			<transformation type="valueUpdate" id="#ID-2"
				name="occupied" value="false" />
			<transformation type="valueUpdate" id="#ID-3"
				name="occupied" value="true" />
		</transformations>
	</element>
	<element>
		<operation name="Движение влево" />
		<objects>
			<object name="материальная точка" id="#ID-1">
				<links>
					<link name="position" value="#ID-3" />
				</links>
			</object>
			<object name="точка" id="#ID-2">
				<attributes>
					<attribute name="occupied" type="boolean" value="false" />
				</attributes>
				<links>
					<link name="right-neighbor" value="#ID-3" />
				</links>
			</object>
			<object name="точка" id="#ID-3">
				<attributes>
					<attribute name="occupied" type="boolean" value="true" />
				</attributes>
				<links>
					<link name="left-neighbor" value="#ID-2" />
					<link name="position" value="#ID-1" />
				</links>
			</object>
		</objects>
		<transformations>
			<transformation type="linkUpdate" id="#ID-1"
				name="position" value="#ID-2" />
			<transformation type="linkUpdate" id="#ID-2"
				name="position" value="#ID-1" />
			<transformation type="linkUpdate" id="#ID-3"
				name="position" value="" />
			<transformation type="valueUpdate" id="#ID-2"
				name="occupied" value="true" />
			<transformation type="valueUpdate" id="#ID-3"
				name="occupied" value="false" />
		</transformations>
	</element>
</elements>
