=== kinnder/process-engineering/planning/src/test/resources/systemTransformations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<xs:annotation>
		<xs:documentation>xml.mherman.org</xs:documentation>
	</xs:annotation>
	<xs:import namespace="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="xsi.xsd" />
	<xs:element name="systemTransformations">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="systemTransformation" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="systemTransformation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="systemTemplate" />
				<xs:element ref="transformations" />
				<xs:element ref="action" />
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:NCName" />
		</xs:complexType>
	</xs:element>
	<xs:element name="systemTemplate">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="objectTemplates" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="objectTemplates">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="objectTemplate" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="objectTemplate">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="attributeTemplates" />
				<xs:element minOccurs="0" ref="linkTemplates" />
			</xs:sequence>
			<xs:attribute name="id" use="required" type="xs:NCName" />
		</xs:complexType>
	</xs:element>
	<xs:element name="attributeTemplates">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="attributeTemplate" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="attributeTemplate">
		<xs:complexType>
			<xs:attribute name="name" use="required" type="xs:NCName" />
			<xs:attribute name="value" type="xs:boolean" />
		</xs:complexType>
	</xs:element>
	<xs:element name="linkTemplates">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="linkTemplate" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="linkTemplate">
		<xs:complexType>
			<xs:attribute name="name" use="required" type="xs:NCName" />
			<xs:attribute name="value" use="required" type="xs:NCName" />
		</xs:complexType>
	</xs:element>
	<xs:element name="transformations">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="transformation" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="transformation">
		<xs:complexType>
			<xs:attribute name="attributeName" />
			<xs:attribute name="attributeValue" type="xs:boolean" />
			<xs:attribute name="linkName" type="xs:NCName" />
			<xs:attribute name="linkNewValue" type="xs:NCName" />
			<xs:attribute name="linkOldValue" type="xs:NCName" />
			<xs:attribute name="objectId" use="required" type="xs:NCName" />
			<xs:attribute name="type" use="required" type="xs:NCName" />
		</xs:complexType>
	</xs:element>
	<xs:element name="action">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="preConditionCheckers" />
				<xs:element minOccurs="0" ref="parameterUpdaters" />
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:NCName" />
		</xs:complexType>
	</xs:element>
	<xs:element name="preConditionCheckers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="preConditionChecker" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="preConditionChecker" type="script" />
	<xs:element name="parameterUpdaters">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parameterUpdater" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="parameterUpdater" type="script" />
	<xs:complexType name="script">
		<xs:sequence>
			<xs:element ref="script" />
		</xs:sequence>
	</xs:complexType>
	<xs:element name="script">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="line" />
			</xs:sequence>
			<xs:attribute name="type" use="required" type="xs:NCName" />
		</xs:complexType>
	</xs:element>
	<xs:element name="line">
		<xs:complexType mixed="true">
			<xs:attribute name="n" use="required" type="xs:integer" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== kinnder/process-engineering/planning/src/test/resources/cuttingProcess/systemTransformations.xml
<?xml version="1.0" encoding="UTF-8"?>
<systemTransformations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../systemTransformations.xsd">
	<systemTransformation name="ELEMENT-CUT-CYLINDER-SURFACE">
		<systemTemplate>
			<objectTemplates>
				<objectTemplate id="ID-WORKPIECE">
					<attributeTemplates>
						<attributeTemplate name="ATTRIBUTE-WORKPIECE" value="true" />
					</attributeTemplates>
					<linkTemplates>
						<linkTemplate name="LINK-IS-PART-OF" value="ID-CYLINDER-SURFACE" />
						<linkTemplate name="LINK-IS-REQUIREMENT-OF" value="ID-REQUIREMENT" />
					</linkTemplates>
				</objectTemplate>
				<objectTemplate id="ID-CYLINDER-SURFACE">
					<attributeTemplates>
						<attributeTemplate name="ATTRIBUTE-CYLINDER-SURFACE" value="true" />
						<attributeTemplate name="ATTRIBUTE-DIAMETER" />
						<attributeTemplate name="ATTRIBUTE-HAS-DIAMETER-REQUIREMENT" value="false" />
					</attributeTemplates>
					<linkTemplates>
						<linkTemplate name="LINK-IS-PART-OF" value="ID-WORKPIECE" />
						<linkTemplate name="LINK-IS-DIAMETER-REQUIREMENT" value="null" />
					</linkTemplates>
				</objectTemplate>
				<objectTemplate id="ID-REQUIREMENT">
					<attributeTemplates>
						<attributeTemplate name="ATTRIBUTE-REQUIREMENT" value="true"/>
						<attributeTemplate name="ATTRIBUTE-REQUIREMENT" />
						<attributeTemplate name="ATTRIBUTE-DIAMETER-REQUIREMENT-STATUS" value="false" />
					</attributeTemplates>
					<linkTemplates>
						<linkTemplate name="LINK-IS-REQUIREMENT-OF" value="ID-WORKPIECE" />
						<linkTemplate name="LINK-IS-DIAMETER-REQUIREMENT" value="null" />
					</linkTemplates>
				</objectTemplate>
			</objectTemplates>
		</systemTemplate>
		<transformations>
			<transformation type="attribute" objectId="ID-ROBOT" attributeName="ATTRIBUTE-DIAMETER-REQUIREMENT-STATUS" attributeValue="true" />
			<transformation type="link" objectId="ID-REQUIREMENT" linkName="LINK-IS-DIAMETER-REQUIREMENT" linkOldValue="null" linkNewValue="ID-CYLINDER-SURFACE" />
			<transformation type="link" objectId="ID-CYLINDER-SURFACE" linkName="LINK-IS-DIAMETER-REQUIREMENT" linkOldValue="null" linkNewValue="ID-REQUIREMENT" />
			<transformation type="attribute" objectId="ID-CYLINDER-SURFACE" attributeName="ATTRIBUTE-HAS-DIAMETER-REQUIREMENT" attributeValue="true" />
		</transformations>
			<action name="OPERATION_CUT_CYLINDER_SURFACE">
				<preConditionCheckers>
					<preConditionChecker>
						<script type="lua">
							<line n="1">local systemVariant = ...</line>
							<line n="2">local cylinderSurface_actual = systemVariant:getObjectByIdMatch('ID-CYLINDER-SURFACE')</line>
							<line n="3">local diameter = cylinderSurface_actual:getAttribute('ATTRIBUTE-DIAMETER'):getValueAsInteger()</line>
							<line n="4">local requirement_actual = systemVariant:getObjectByIdMatch('ID-REQUIREMENT')</line>
							<line n="5">local diameterRequired = requirement_actual:getAttribute('ATTRIBUTE-DIAMETER-REQUIREMENT'):getValueAsInteger()</line>
							<line n="6">return diameter > diameterRequired</line>
						</script>
					</preConditionChecker>
				</preConditionCheckers>
				<parameterUpdaters>
					<parameterUpdater>
						<script type="lua">
							<line n="1">local systemVariant = ...</line>
							<line n="2">local cylinderSurface_actual = systemVariant:getObjectByIdMatch('ID-CYLINDER-SURFACE')</line>
							<line n="3">local diameter = cylinderSurface_actual:getAttribute('ATTRIBUTE-DIAMETER'):getValueAsInteger()</line>
							<line n="4">local requirement_actual = systemVariant:getObjectByIdMatch('ID-REQUIREMENT')</line>
							<line n="5">local diameterRequired = requirement_actual:getAttribute('ATTRIBUTE-DIAMETER-REQUIREMENT'):getValueAsInteger()</line>
							<line n="6">local diameterDelta = diameter - diameterRequired</line>
							<line n="7">systemVariant:setActionParameter('PARAMETER-DIAMETER-DELTA', diameterDelta)</line>
							<line n="8">cylinderSurface_actual:getAttribute('ATTRIBUTE-DIAMETER'):setValue(diameterRequired)</line>
						</script>
					</parameterUpdater>
				</parameterUpdaters>
			</action>
	</systemTransformation>
</systemTransformations>

=== kinnder/process-engineering/planning/src/test/resources/materialPoints/systemTransformations.xml
<?xml version="1.0" encoding="UTF-8"?>
<systemTransformations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../systemTransformations.xsd">
	<systemTransformation name="ELEMENT-MOVE-RIGHT">
		<systemTemplate>
			<objectTemplates>
				<objectTemplate id="ID-OBJECT">
					<linkTemplates>
						<linkTemplate name="LINK-POSITION" value="ID-POINT-A" />
					</linkTemplates>
				</objectTemplate>
				<objectTemplate id="ID-POINT-A">
					<attributeTemplates>
						<attributeTemplate name="ATTRIBUTE-OCCUPIED" value="true" />
					</attributeTemplates>
					<linkTemplates>
						<linkTemplate name="LINK-NEIGHBOR-RIGHT" value="ID-POINT-B" />
						<linkTemplate name="LINK-POSITION" value="ID-OBJECT" />
					</linkTemplates>
				</objectTemplate>
				<objectTemplate id="ID-POINT-B">
					<attributeTemplates>
						<attributeTemplate name="ATTRIBUTE-OCCUPIED" value="false" />
					</attributeTemplates>
					<linkTemplates>
						<linkTemplate name="LINK-NEIGHBOR-LEFT" value="ID-POINT-A" />
					</linkTemplates>
				</objectTemplate>
			</objectTemplates>
		</systemTemplate>
		<transformations>
			<transformation type="link" objectId="ID-OBJECT" linkName="LINK-POSITION" linkOldValue="ID-POINT-A" linkNewValue="ID-POINT-B" />
			<transformation type="link" objectId="ID-POINT-A" linkName="LINK-POSITION" linkOldValue="ID-OBJECT" linkNewValue="null" />
			<transformation type="link" objectId="ID-POINT-B" linkName="LINK-POSITION" linkOldValue="null" linkNewValue="ID-OBJECT" />
			<transformation type="attribute" objectId="ID-POINT-A" attributeName="ATTRIBUTE-OCCUPIED" attributeValue="false" />
			<transformation type="attribute" objectId="ID-POINT-B" attributeName="ATTRIBUTE-OCCUPIED" attributeValue="true" />
		</transformations>
		<action name="OPERATION-MOVE-RIGHT" />
	</systemTransformation>
	<systemTransformation name="ELEMENT-MOVE-LEFT">
		<systemTemplate>
			<objectTemplates>
				<objectTemplate id="ID-OBJECT">
					<linkTemplates>
						<linkTemplate name="LINK-POSITION" value="ID-POINT-B" />
					</linkTemplates>
				</objectTemplate>
				<objectTemplate id="ID-POINT-A">
					<attributeTemplates>
						<attributeTemplate name="ATTRIBUTE-OCCUPIED" value="false" />
					</attributeTemplates>
					<linkTemplates>
						<linkTemplate name="LINK-NEIGHBOR-RIGHT" value="ID-POINT-B" />
					</linkTemplates>
				</objectTemplate>
				<objectTemplate id="ID-POINT-B">
					<attributeTemplates>
						<attributeTemplate name="ATTRIBUTE-OCCUPIED" value="true" />
					</attributeTemplates>
					<linkTemplates>
						<linkTemplate name="LINK-NEIGHBOR-LEFT" value="ID-POINT-A" />
						<linkTemplate name="LINK-POSITION" value="ID-OBJECT" />
					</linkTemplates>
				</objectTemplate>
			</objectTemplates>
		</systemTemplate>
		<transformations>
			<transformation type="link" objectId="ID-OBJECT" linkName="LINK-POSITION" linkOldValue="ID-POINT-B" linkNewValue="ID-POINT-A" />
			<transformation type="link" objectId="ID-POINT-A" linkName="LINK-POSITION" linkOldValue="null" linkNewValue="ID-OBJECT" />
			<transformation type="link" objectId="ID-POINT-B" linkName="LINK-POSITION" linkOldValue="ID-OBJECT" linkNewValue="null" />
			<transformation type="attribute" objectId="ID-POINT-A" attributeName="ATTRIBUTE-OCCUPIED" attributeValue="true" />
			<transformation type="attribute" objectId="ID-POINT-B" attributeName="ATTRIBUTE-OCCUPIED" attributeValue="false" />
		</transformations>
		<action name="OPERATION-MOVE-LEFT" />
	</systemTransformation>
	<systemTransformation name="ELEMENT-MOVE-TOP">
		<systemTemplate>
			<objectTemplates>
				<objectTemplate id="ID-OBJECT">
					<linkTemplates>
						<linkTemplate name="LINK-POSITION" value="ID-POINT-A" />
					</linkTemplates>
				</objectTemplate>
				<objectTemplate id="ID-POINT-A">
					<attributeTemplates>
						<attributeTemplate name="ATTRIBUTE-OCCUPIED" value="true" />
					</attributeTemplates>
					<linkTemplates>
						<linkTemplate name="LINK-NEIGHBOR-TOP" value="ID-POINT-B" />
						<linkTemplate name="LINK-POSITION" value="ID-OBJECT" />
					</linkTemplates>
				</objectTemplate>
				<objectTemplate id="ID-POINT-B">
					<attributeTemplates>
						<attributeTemplate name="ATTRIBUTE-OCCUPIED" value="false" />
					</attributeTemplates>
					<linkTemplates>
						<linkTemplate name="LINK-NEIGHBOR-BOTTOM" value="ID-POINT-A" />
					</linkTemplates>
				</objectTemplate>
			</objectTemplates>
		</systemTemplate>
		<transformations>
			<transformation type="link" objectId="ID-OBJECT" linkName="LINK-POSITION" linkOldValue="ID-POINT-A" linkNewValue="ID-POINT-B" />
			<transformation type="link" objectId="ID-POINT-A" linkName="LINK-POSITION" linkOldValue="ID-OBJECT" linkNewValue="null" />
			<transformation type="link" objectId="ID-POINT-B" linkName="LINK-POSITION" linkOldValue="null" linkNewValue="ID-OBJECT" />
			<transformation type="attribute" objectId="ID-POINT-A" attributeName="ATTRIBUTE-OCCUPIED" attributeValue="false" />
			<transformation type="attribute" objectId="ID-POINT-B" attributeName="ATTRIBUTE-OCCUPIED" attributeValue="true" />
		</transformations>
		<action name="OPERATION-MOVE-TOP" />
	</systemTransformation>
	<systemTransformation name="ELEMENT-MOVE-BOTTOM">
		<systemTemplate>
			<objectTemplates>
				<objectTemplate id="ID-OBJECT">
					<linkTemplates>
						<linkTemplate name="LINK-POSITION" value="ID-POINT-B" />
					</linkTemplates>
				</objectTemplate>
				<objectTemplate id="ID-POINT-A">
					<attributeTemplates>
						<attributeTemplate name="ATTRIBUTE-OCCUPIED" value="false" />
					</attributeTemplates>
					<linkTemplates>
						<linkTemplate name="LINK-NEIGHBOR-TOP" value="ID-POINT-B" />
					</linkTemplates>
				</objectTemplate>
				<objectTemplate id="ID-POINT-B">
					<attributeTemplates>
						<attributeTemplate name="ATTRIBUTE-OCCUPIED" value="true" />
					</attributeTemplates>
					<linkTemplates>
						<linkTemplate name="LINK-NEIGHBOR-BOTTOM" value="ID-POINT-A" />
						<linkTemplate name="LINK-POSITION" value="ID-OBJECT" />
					</linkTemplates>
				</objectTemplate>
			</objectTemplates>
		</systemTemplate>
		<transformations>
			<transformation type="link" objectId="ID-OBJECT" linkName="LINK-POSITION" linkOldValue="ID-POINT-B" linkNewValue="ID-POINT-A" />
			<transformation type="link" objectId="ID-POINT-A" linkName="LINK-POSITION" linkOldValue="null" linkNewValue="ID-OBJECT" />
			<transformation type="link" objectId="ID-POINT-B" linkName="LINK-POSITION" linkOldValue="ID-OBJECT" linkNewValue="null" />
			<transformation type="attribute" objectId="ID-POINT-A" attributeName="ATTRIBUTE-OCCUPIED" attributeValue="true" />
			<transformation type="attribute" objectId="ID-POINT-B" attributeName="ATTRIBUTE-OCCUPIED" attributeValue="false" />
		</transformations>
		<action name="OPERATION-MOVE-BOTTOM" />
	</systemTransformation>
</systemTransformations>

=== kinnder/process-engineering/planning/src/test/resources/assemblyLine/systemTransformations.xml
<?xml version="1.0" encoding="UTF-8"?>
<systemTransformations
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../systemTransformations.xsd">
	<systemTransformation
		name="ELEMENT-TURN-WITHOUT-LOAD">
		<systemTemplate>
			<objectTemplates>
				<objectTemplate id="ID-ROBOT">
					<attributeTemplates>
						<attributeTemplate name="ATTRIBUTE-PICK-AND-PLACE-ROBOT" value="true" />
					</attributeTemplates>
					<linkTemplates>
						<linkTemplate name="LINK-ROTARY-DRIVE-POSITION" value="ID-PLANE-Y-SOURCE" />
						<linkTemplate name="LINK-GRAB-POSITION" value="null" />
					</linkTemplates>
				</objectTemplate>
				<objectTemplate id="ID-PLANE-Y-TARGET">
					<attributeTemplates>
						<attributeTemplate name="ATTRIBUTE-PLANE-Y" value="true" />
					</attributeTemplates>
					<linkTemplates>
						<linkTemplate name="LINK-ROTARY-DRIVE-POSITION" value="ID-ROBOT" />
					</linkTemplates>
				</objectTemplate>
				<objectTemplate id="ID-PLANE-Y-SOURCE">
					<attributeTemplates>
						<attributeTemplate name="ATTRIBUTE-PLANE-Y" value="true" />
					</attributeTemplates>
					<linkTemplates>
						<linkTemplate name="LINK-ROTARY-DRIVE-POSITION" value="null" />
					</linkTemplates>
				</objectTemplate>
			</objectTemplates>
		</systemTemplate>
		<transformations>
			<transformation type="link" objectId="ID-ROBOT" linkName="LINK-ROTARY-DRIVE-POSITION" linkOldValue="ID-PLANE-Y-SOURCE" linkNewValue="ID-PLANE-Y-TARGET" />
			<transformation type="link" objectId="ID-PLANE-Y-TARGET" linkName="LINK-ROTARY-DRIVE-POSITION" linkOldValue="null" linkNewValue="ID-ROBOT" />
			<transformation type="link" objectId="ID-PLANE-Y-SOURCE" linkName="LINK-ROTARY-DRIVE-POSITION" linkOldValue="ID-ROBOT" linkNewValue="null" />
		</transformations>
		<action name="OPERATION-TURN-WITHOUT-LOAD">
			<parameterUpdaters>
				<parameterUpdater>
					<script type="lua">
						<line n="1">local systemVariant = ...</line>
						<line n="2">local object = systemVariant:getObjectByIdMatch('ID-PLANE-Y-TARGET')</line>
						<line n="3">systemVariant:setActionParameter('PARAMETER_TARGET',object:getName())</line>
					</script>
				</parameterUpdater>
			</parameterUpdaters>
		</action>
	</systemTransformation>
</systemTransformations>
