=== kinnder/process-engineering/planning/src/test/resources/taskDescription.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<xs:annotation>
		<xs:documentation>xml.mherman.org</xs:documentation>
	</xs:annotation>
	<xs:import namespace="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="xsi.xsd" />
	<xs:element name="taskDescription">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="initialSystem" />
				<xs:element ref="finalSystem" />
			</xs:sequence>
			<xs:attribute ref="xsi:noNamespaceSchemaLocation" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="initialSystem">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="systemObject" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="finalSystem">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="systemObject" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="systemObject">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name" />
				<xs:element ref="id" />
				<xs:element ref="attribute" />
				<xs:element maxOccurs="unbounded" ref="link" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="id" type="xs:string" />
	<xs:element name="attribute">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name" />
				<xs:element ref="value" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="value">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:NCName">
					<xs:attribute name="type">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="boolean" />
								<xs:enumeration value="string" />
								<xs:enumeration value="integer" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="link">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" />
				<xs:element minOccurs="0" name="objectId" type="xs:NCName" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== kinnder/process-engineering/planning/src/test/resources/cuttingProcess/taskDescription.xml
<?xml version="1.0" encoding="UTF-8"?>
<taskDescription xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../taskDescription.xsd">
	<initialSystem>
		<systemObject>
			<name>OBJECT-WORKPIECE</name>
			<id>5aede79b-ea03-4785-9173-42c7fcafc2ca</id>
			<attribute>
				<name>ATTRIBUTE-WORKPIECE</name>
				<value type="boolean">true</value>
			</attribute>
			<link>
				<name>LINK-IS-PART-OF</name>
				<objectId1>7492e4eb-1417-4d51-befc-b1ddf0d312a2</objectId1>
			</link>
			<link>
				<name>LINK-IS-REQUIREMENT-OF</name>
				<objectId1>95450425-7a47-4d0b-910e-4f0eb56a4fab</objectId1>
			</link>
			<link>
				<name>LINK-IS-REQUIREMENT-OF</name>
				<objectId1>5adc3980-e565-42a2-8bc0-bcc1e79d37a5</objectId1>
			</link>
			<link>
				<name>LINK-IS-REQUIREMENT-OF</name>
				<objectId1>ead2c426-1edb-4dbe-93c3-ba8192cefd68</objectId1>
			</link>
		</systemObject>
		<systemObject>
			<name>OBJECT-CYLINDER-SURFACE</name>
			<id>7492e4eb-1417-4d51-befc-b1ddf0d312a2</id>
			<attribute>
				<name>ATTRIBUTE-LENGTH</name>
				<value type="integer">90</value>
			</attribute>
			<attribute>
				<name>ATTRIBUTE-HAS-LENGTH-REQUIREMENT</name>
				<value type="boolean">false</value>
			</attribute>
			<attribute>
				<name>ATTRIBUTE-DIAMETER</name>
				<value type="integer">22</value>
			</attribute>
			<attribute>
				<name>ATTRIBUTE-CYLINDER-SURFACE</name>
				<value type="boolean">true</value>
			</attribute>
			<attribute>
				<name>ATTRIBUTE-HAS-DIAMETER-REQUIREMENT</name>
				<value type="boolean">false</value>
			</attribute>
			<link>
				<name>LINK-IS-PART-OF</name>
				<objectId1>5aede79b-ea03-4785-9173-42c7fcafc2ca</objectId1>
			</link>
			<link>
				<name>LINK-IS-DIAMETER-REQUIREMENT</name>
			</link>
			<link>
				<name>LINK-IS-LENGTH-REQUIREMENT</name>
			</link>
		</systemObject>
		<systemObject>
			<name>OBJECT-REQUIREMENT-SURFACE-A</name>
			<id>95450425-7a47-4d0b-910e-4f0eb56a4fab</id>
			<attribute>
				<name>ATTRIBUTE-REQUIREMENT</name>
				<value type="boolean">true</value>
			</attribute>
			<attribute>
				<name>ATTRIBUTE-DIAMETER-REQUIREMENT-STATUS</name>
				<value type="boolean">false</value>
			</attribute>
			<attribute>
				<name>ATTRIBUTE-DIAMETER-REQUIREMENT</name>
				<value type="integer">20</value>
			</attribute>
			<attribute>
				<name>ATTRIBUTE-LENGTH-REQUIREMENT-STATUS</name>
				<value type="boolean">false</value>
			</attribute>
			<attribute>
				<name>ATTRIBUTE-LENGTH-REQUIREMENT</name>
				<value type="integer">45</value>
			</attribute>
			<link>
				<name>LINK-IS-REQUIREMENT-OF</name>
				<objectId1>5aede79b-ea03-4785-9173-42c7fcafc2ca</objectId1>
			</link>
			<link>
				<name>LINK-IS-DIAMETER-REQUIREMENT</name>
			</link>
			<link>
				<name>LINK-IS-LENGTH-REQUIREMENT</name>
			</link>
			<link>
				<name>LINK-SURFACE-SIDE-LEFT</name>
			</link>
			<link>
				<name>LINK-SURFACE-SIDE-RIGHT</name>
				<objectId1>5adc3980-e565-42a2-8bc0-bcc1e79d37a5</objectId1>
			</link>
		</systemObject>
		<systemObject>
			<name>OBJECT-REQUIREMENT-SURFACE-B</name>
			<id>5adc3980-e565-42a2-8bc0-bcc1e79d37a5</id>
			<attribute>
				<name>ATTRIBUTE-REQUIREMENT</name>
				<value type="boolean">true</value>
			</attribute>
			<attribute>
				<name>ATTRIBUTE-DIAMETER-REQUIREMENT-STATUS</name>
				<value type="boolean">false</value>
			</attribute>
			<attribute>
				<name>ATTRIBUTE-DIAMETER-REQUIREMENT</name>
				<value type="integer">16</value>
			</attribute>
			<attribute>
				<name>ATTRIBUTE-LENGTH-REQUIREMENT-STATUS</name>
				<value type="boolean">false</value>
			</attribute>
			<attribute>
				<name>ATTRIBUTE-LENGTH-REQUIREMENT</name>
				<value type="integer">30</value>
			</attribute>
			<link>
				<name>LINK-IS-REQUIREMENT-OF</name>
				<objectId1>5aede79b-ea03-4785-9173-42c7fcafc2ca</objectId1>
			</link>
			<link>
				<name>LINK-IS-DIAMETER-REQUIREMENT</name>
			</link>
			<link>
				<name>LINK-IS-LENGTH-REQUIREMENT</name>
			</link>
			<link>
				<name>LINK-SURFACE-SIDE-LEFT</name>
				<objectId1>95450425-7a47-4d0b-910e-4f0eb56a4fab</objectId1>
			</link>
			<link>
				<name>LINK-SURFACE-SIDE-RIGHT</name>
				<objectId1>ead2c426-1edb-4dbe-93c3-ba8192cefd68</objectId1>
			</link>
		</systemObject>
		<systemObject>
			<name>OBJECT-REQUIREMENT-SURFACE-C</name>
			<id>ead2c426-1edb-4dbe-93c3-ba8192cefd68</id>
			<attribute>
				<name>ATTRIBUTE-REQUIREMENT</name>
				<value type="boolean">true</value>
			</attribute>
			<attribute>
				<name>ATTRIBUTE-DIAMETER-REQUIREMENT-STATUS</name>
				<value type="boolean">false</value>
			</attribute>
			<attribute>
				<name>ATTRIBUTE-DIAMETER-REQUIREMENT</name>
				<value type="integer">12</value>
			</attribute>
			<attribute>
				<name>ATTRIBUTE-LENGTH-REQUIREMENT-STATUS</name>
				<value type="boolean">false</value>
			</attribute>
			<attribute>
				<name>ATTRIBUTE-LENGTH-REQUIREMENT</name>
				<value type="integer">15</value>
			</attribute>
			<link>
				<name>LINK-IS-REQUIREMENT-OF</name>
				<objectId1>5aede79b-ea03-4785-9173-42c7fcafc2ca</objectId1>
			</link>
			<link>
				<name>LINK-IS-DIAMETER-REQUIREMENT</name>
			</link>
			<link>
				<name>LINK-IS-LENGTH-REQUIREMENT</name>
			</link>
			<link>
				<name>LINK-SURFACE-SIDE-LEFT</name>
				<objectId1>5adc3980-e565-42a2-8bc0-bcc1e79d37a5</objectId1>
			</link>
			<link>
				<name>LINK-SURFACE-SIDE-RIGHT</name>
			</link>
		</systemObject>
	</initialSystem>
	<finalSystem>
		<systemObject>
			<name>OBJECT-REQUIREMENT-SURFACE-A</name>
			<id>95450425-7a47-4d0b-910e-4f0eb56a4fab</id>
			<attribute>
				<name>ATTRIBUTE-REQUIREMENT</name>
				<value type="boolean">true</value>
			</attribute>
			<attribute>
				<name>ATTRIBUTE-DIAMETER-REQUIREMENT-STATUS</name>
				<value type="boolean">true</value>
			</attribute>
			<attribute>
				<name>ATTRIBUTE-LENGTH-REQUIREMENT-STATUS</name>
				<value type="boolean">true</value>
			</attribute>
			<link>
				<name>LINK-IS-REQUIREMENT-OF</name>
				<objectId1>5aede79b-ea03-4785-9173-42c7fcafc2ca</objectId1>
			</link>
			<link>
				<name>LINK-SURFACE-SIDE-LEFT</name>
			</link>
			<link>
				<name>LINK-SURFACE-SIDE-RIGHT</name>
				<objectId1>5adc3980-e565-42a2-8bc0-bcc1e79d37a5</objectId1>
			</link>
		</systemObject>
		<systemObject>
			<name>OBJECT-REQUIREMENT-SURFACE-B</name>
			<id>5adc3980-e565-42a2-8bc0-bcc1e79d37a5</id>
			<attribute>
				<name>ATTRIBUTE-REQUIREMENT</name>
				<value type="boolean">true</value>
			</attribute>
			<attribute>
				<name>ATTRIBUTE-DIAMETER-REQUIREMENT-STATUS</name>
				<value type="boolean">true</value>
			</attribute>
			<attribute>
				<name>ATTRIBUTE-LENGTH-REQUIREMENT-STATUS</name>
				<value type="boolean">true</value>
			</attribute>
			<link>
				<name>LINK-IS-REQUIREMENT-OF</name>
				<objectId1>5aede79b-ea03-4785-9173-42c7fcafc2ca</objectId1>
			</link>
			<link>
				<name>LINK-SURFACE-SIDE-LEFT</name>
				<objectId1>95450425-7a47-4d0b-910e-4f0eb56a4fab</objectId1>
			</link>
			<link>
				<name>LINK-SURFACE-SIDE-RIGHT</name>
				<objectId1>ead2c426-1edb-4dbe-93c3-ba8192cefd68</objectId1>
			</link>
		</systemObject>
		<systemObject>
			<name>OBJECT-REQUIREMENT-SURFACE-C</name>
			<id>ead2c426-1edb-4dbe-93c3-ba8192cefd68</id>
			<attribute>
				<name>ATTRIBUTE-REQUIREMENT</name>
				<value type="boolean">true</value>
			</attribute>
			<attribute>
				<name>ATTRIBUTE-DIAMETER-REQUIREMENT-STATUS</name>
				<value type="boolean">true</value>
			</attribute>
			<attribute>
				<name>ATTRIBUTE-LENGTH-REQUIREMENT-STATUS</name>
				<value type="boolean">true</value>
			</attribute>
			<link>
				<name>LINK-IS-REQUIREMENT-OF</name>
				<objectId1>5aede79b-ea03-4785-9173-42c7fcafc2ca</objectId1>
			</link>
			<link>
				<name>LINK-SURFACE-SIDE-LEFT</name>
				<objectId1>5adc3980-e565-42a2-8bc0-bcc1e79d37a5</objectId1>
			</link>
			<link>
				<name>LINK-SURFACE-SIDE-RIGHT</name>
			</link>
		</systemObject>
	</finalSystem>
</taskDescription>
